name: some-checks
on: [push]

jobs:
  check:
    name: some-second-checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Run script
        run: python3.9 main.py